version: '3.9'

services:
  app:
    container_name: praxis-lp
    build:
      context: .
      target: runtime_stage
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    env_file: .env
